version: '3.8'

services:
  # 1. CỤC DATABASE
  mysql-db:
    image: mysql:8.0.41-debian
    container_name: posture_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posture_checker_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - posture_network
    # --- THÊM KHỐI NÀY ĐỂ KIỂM TRA SỨC KHỎE MYSQL ---
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10

  # 2. CỤC BACKEND SPRING BOOT
  spring-backend:
    build: .
    container_name: posture_backend
    ports:
      - "8080:8080"
    depends_on:
      # --- SỬA LẠI KHÚC NÀY ĐỂ BẮT SPRING BOOT PHẢI CHỜ ---
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/posture_checker_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - posture_network

volumes:
  mysql_data:

networks:
  posture_network:
    driver: bridge